### ISSUE TITLE
URL requests

### ISSUE THREAD

**Issue by systwi-again** [ArchiveTeam/mediafire-items#5]
Hi, I'd like to add the following URLs to the project:

- ```http://www.mediafire.com/download/3ll2zfpy2v3e47p/VhdTool.zip```, from [this Spiceworks thread](https://community.spiceworks.com/topic/501507-need-link-to-vhdtool-exe-download).
- ```https://www.mediafire.com/file/0zeapcehs0sokvh/srrgui-1.3.zip/file```, from [srrDB's homepage](https://www.srrdb.com).

Thank you!

**Comment by Arkiver2** [comment]
thank you @systwi-again, added them here https://github.com/ArchiveTeam/mediafire-items/blob/master/raw/issue-5.txt

**Comment by Arkiver2** [comment]
these have been queued
